version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./bidding.db
      - SECRET_KEY=your_secret_key_for_jwt_should_be_changed_in_production
    command: >
      sh -c "pipenv install --dev &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 